### ISSUE TITLE
Organizar o Roadmap do ZenHub

### ISSUE THREAD

**Issue by igor-paiva** [fga-eps-mds/2021-2-MeasureSoftGram-Doc#115]
## Descrição da atividade
Organizar o Roadmap do ZenHub.

## Lista de afazeres
1. [x] Definir e adicionar os projetos
2. [x] Adicionar os épicos correspondentes a cada projeto
3. [x] Verificar se está tudo correto
