### ISSUE TITLE
Incorporar as entradas

### ISSUE THREAD

**Issue by igor-paiva** [fga-eps-mds/2021-2-MeasureSoftGram-Doc#49]
## Descrição

**Habilitador técnico**

Incorporar as entradas (características, sub-características, funções de interpretação, métricas e valores de referência), baseadas no notebook do MeasureSoftGram, para que seja possível inserir as métricas e o sistema possa fazer a análise utilizando as entradas incorporadas.

## Critérios de aceitação

- [ ] Retornar uma medida dado as métricas
    - Dado um conjunto de métricas
    - Quando a função de interpretação for executada
    - Então a medida (valor) deve ser retornado
- [ ] Retornar lista de sub-características
    - Dado que o nome da característica é válido
    - Quando a lista for solicitada
    - Então a lista com as sub-características deve ser retornada

## Tarefas

- [ ] Selecionar métricas apresentadas no notebook
- [ ] Criar lista de características e sub-características
- [ ] Implementar as funções de intepretação
